databases:
  - name: project_nexus_db
    databaseName: project_nexus
    user: project_nexus

services:
  - type: web
    name: project_nexus
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project_nexus_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "false"
